set(__QT_DEPLOY_TARGET_minigit_gui_FILE C:/Users/eshan/OneDrive/Documents/Minigit/dist/minigit_gui.exe)
set(__QT_DEPLOY_TARGET_minigit_gui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_minigit_gui_RUNTIME_DLLS C:/Qt/6.11.0/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.11.0/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.11.0/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_minigit_smoke_tests_FILE C:/Users/eshan/OneDrive/Documents/Minigit/build_mingw/minigit_smoke_tests.exe)
set(__QT_DEPLOY_TARGET_minigit_smoke_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_minigit_smoke_tests_RUNTIME_DLLS )
